### ISSUE TITLE
Doesn't work with relative paths

### ISSUE THREAD

**Issue by pedrocr** [hoxu/dokuwiki2git#3]
I tried running the script with "./dokuwiki2git data" as I had downloaded the data dir into a local file and it failed trying to access a file that was actually there. Giving it a full path made it work. Running "./dokuwiki2git ./data" doesn't work either.

**Comment by hoxu** [comment]
Not reproducible with these details, so closing. "doesn't work" generally does not go into great lengths at explaining the problem.

Please reopen if you can still reproduce the issue and provide the following information:
1) full terminal output with "-v" parameter, including the command you run, and the traceback
2) OS and version
3) python version
4) Filesystem type (ext3/4 or cryptfs/encfs or similar?)

**Comment by hoxu** [comment]
I'll take that back, I think I've reproduced the issue :)

**Comment by hoxu** [comment]
Fixed in dca16e4732fc12e074ba5efda2afbbd4e5d50215, thanks for reporting the issue!

**Comment by pedrocr** [comment]
Thanks for looking into it and sorry for not including at least the shell output. It was late I wasn't thinking straight. Besides this easily avoidable bug the script worked fine. Migrated to gollum in no time. Thanks!
